app = "sandlot-bc9nta"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
PORT = "4001"

[[services]]
  internal_port = 4001
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
